### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by 18850947** [pattern-inc/cynetworkx#1]
I am trying to install cynetworkx on windows 10, using python 3.6 32 bit distribution of winpy, however I am getting the following error:

> failed to build wheel for cynetworkx

followed by:

> LINK : error LNK2001: unresolved external symbol PyInit___init__
>     build\temp.win32-3.6\Release\cynetworkx/algorithms/approximation\__init__.cp36-win32.lib : fatal error LNK1120: 1 unresolved externals
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120

I have attached the entire output as a text document as it is quite long and there is a lot of lines between the two errors. [ouput.txt](https://github.com/pattern-inc/cynetworkx/files/3558643/ouput.txt)
I have also tried to install using python 3.6 64 bit, installing with and without scipy extentions, reinstalling python all together.
from my understanding the second error is caused by a pyinit___init___ line needing to be changed to pyinit___cynetworkx___ to be compatible with windows, as described [here](https://bugs.python.org/issue35893) but I am unsure how to fix in this case.

**Comment by NimpNaw** [comment]
I have the same issue. Did you find a solution ?

**Comment by 18850947** [comment]
Unfortunately not. I reverted to using networkx and finding other optimizations in my code to get the speed improvements I wanted. It does install on linux fine though

**Comment by elfmimi** [comment]
This PR at cython pre-release branch addresses that issue. https://github.com/cython/cython/pull/2795

You can install the current pre-release of Cython doing like the following.
```pip install Cython=3.0a5```

and then you can build and install cynetworkx from source doing like this.
```pip install git+https://github.com/pattern-inc/cynetworkx.git```

**Comment by JaeDukSeo** [comment]
This is a great fix, amazing, just takes a while for the package to build on windows

**Comment by otakucore** [comment]
I get the same wall of red text, no change after installing Cython 3.0a5.  It ends with error: Microsoft Visual C++ 14.0 or greater is required, but I've downloaded and installed C++ build tools like it says to.  I'm trying installing _everything_ now.

**Comment by Entretoize** [comment]
Doesn't work for me on windows 10:

```
H:\git\3dphotoinpainting>pip install git+https://github.com/pattern-inc/cynetworkx.git
Collecting git+https://github.com/pattern-inc/cynetworkx.git
  Cloning https://github.com/pattern-inc/cynetworkx.git to c:\users\greg\appdata\local\temp\pip-req-build-5ikq_y5k
  Running command git clone --filter=blob:none -q https://github.com/pattern-inc/cynetworkx.git 'C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k'
  Resolved https://github.com/pattern-inc/cynetworkx.git to commit 7120238fa70cfadbb34532cd37de1280a799a78e
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'H:\miniconda\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Greg\\AppData\\Local\\Temp\\pip-req-build-5ikq_y5k\\setup.py'"'"'; __file__='"'"'C:\\Users\\Greg\\AppData\\Local\\Temp\\pip-req-build-5ikq_y5k\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Greg\AppData\Local\Temp\pip-pip-egg-info-tsjw1gpq'
       cwd: C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\
  Complete output (17 lines):
  C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\cynetworkx\convert_matrix.py:566: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if python_type is 'void':
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\setup.py", line 31, in <module>
      import cynetworkx.release as release
    File "C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\cynetworkx\__init__.py", line 85, in <module>
      import cynetworkx.generators
    File "C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\cynetworkx\generators\__init__.py", line 14, in <module>
      from cynetworkx.generators.intersection import *
    File "C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\cynetworkx\generators\intersection.py", line 13, in <module>
      from cynetworkx.algorithms import bipartite
    File "C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\cynetworkx\algorithms\__init__.py", line 16, in <module>
      from cynetworkx.algorithms.dag import *
    File "C:\Users\Greg\AppData\Local\Temp\pip-req-build-5ikq_y5k\cynetworkx\algorithms\dag.py", line 23, in <module>
      from fractions import gcd
  ImportError: cannot import name 'gcd' from 'fractions' (H:\miniconda\lib\fractions.py)
  ----------------------------------------
WARNING: Discarding git+https://github.com/pattern-inc/cynetworkx.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jleaders** [comment]
Windows 11  fails with 
    `LINK : error LNK2001: unresolved external symbol PyInit___init__`

even with `Cython=3.0a5` as suggested above

**Comment by Thomas-MMJ** [comment]
this worked for me, 

```
git clone https://github.com/pattern-inc/cynetworkx
pip install Cython==3.0.0a11
```

then

```
python setup.py clean
python setup.py build
python setup.py bdist_wheel
cd dist
pip install .
```

**Comment by stevieraykatz** [comment]
Amazing timing. I just got stuck on this tonight and this worked. Thank you

**Comment by Entretoize** [comment]
Seems to have worked for me too, but the commande `pip install .` failed, I did `pip install cynetworkx-2.2rc1.dev20221104064528-cp38-cp38-win_amd64.whl`

**Comment by Thomas-MMJ** [comment]
> Seems to have worked for me too, but the commande `pip install .` failed, I did `pip install cynetworkx-2.2rc1.dev20221104064528-cp38-cp38-win_amd64.whl`

I wonder why,

could also do

`pip install *.whl`
