### ISSUE TITLE
Python 3.9: ImportError: cannot import name 'gcd' from 'fractions'

### ISSUE THREAD

**Issue by Viech** [pattern-inc/cynetworkx#2]
With Python 3.9, `gcd` has moved from `fractions` to `math` after being deprecated since Python 3.5. As a result, `cynetworkx` does not install:

```shell
% pip install --user cynetworkx
Collecting cynetworkx
  Using cached cynetworkx-2.2rc1.dev20180527181709.tar.gz (14.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6qdeqc25
         cwd: /tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/
    Complete output (17 lines):
    /tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/cynetworkx/convert_matrix.py:566: SyntaxWarning: "is" with a literal. Did you mean "=="?
      if python_type is 'void':
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/setup.py", line 31, in <module>
        import cynetworkx.release as release
      File "/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/cynetworkx/__init__.py", line 85, in <module>
        import cynetworkx.generators
      File "/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/cynetworkx/generators/__init__.py", line 14, in <module>
        from cynetworkx.generators.intersection import *
      File "/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/cynetworkx/generators/intersection.py", line 13, in <module>
        from cynetworkx.algorithms import bipartite
      File "/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/cynetworkx/algorithms/__init__.py", line 16, in <module>
        from cynetworkx.algorithms.dag import *
      File "/tmp/pip-install-oe9hf0s2/cynetworkx_d7ec2cb930d74885a44798d0694eb86c/cynetworkx/algorithms/dag.py", line 23, in <module>
        from fractions import gcd
    ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
    ----------------------------------------

```

**Comment by drensin** [comment]
submitted a pull request with a fix.
